{"dependencies":[{"name":"../base","loc":{"line":4,"column":23}}],"generated":{"js":"\"use strict\";\nObject.defineProperty(exports, \"__esModule\", { value: true });\nexports.CustomCondition = void 0;\nconst base_1 = require(\"../base\");\nclass CustomCondition {\n    constructor(condition) {\n        this.condition = condition;\n    }\n    async run(_context, value, meta) {\n        try {\n            const result = this.condition(value, meta);\n            await result;\n            // if the promise resolved or the result is truthy somehow, then there's no validation halt.\n            if (!result) {\n                // the error thrown here is symbolic, it will be re-thrown in the catch clause anyway.\n                throw new Error();\n            }\n        }\n        catch (e) {\n            throw new base_1.ValidationHalt();\n        }\n    }\n}\nexports.CustomCondition = CustomCondition;\n"},"hash":"d3c14f1a5a24650bbb9d78e3c92dc7f8"}